[project]
name="quant-business"
version="1.0.0"
description="A business application for quantitative analysis"
dependencies=[
    "flask",
    "flask_jwt_extended",
    "yfinance",
    "cryptography"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"