DROP TABLE IF EXISTS financial_valuation_ratios;

CREATE TABLE IF EXISTS financial_valuation_ratios (
    symbol TEXT,
    recent_month TEXT,
    
);

DROP TABLE IF EXISTS financial_earning_ratios;

CREATE TABLE IF NOT EXISTS financial_earning_ratios (
    symbol TEXT,
    recent_month TEXT,
    diluted_eps_growth,
    diluted_cont_eps_growth,
    dps_growth,
    equity_per_share_growth,
    regression_growthof_dividends_5_years,
    fcf_per_share_growth,
    book_value_per_share_growth,
    normalized_diluted_eps_growth,
    normalized_basic_eps_growth,
    date TEXT
);

DROP TABLE IF EXISTS financial_operation_ratios;

CREATE TABLE IF NOT EXISTS financial_operation_ratios (
    symbol TEXT,
    recent_month TEXT,
    revenue_growth,
    operation_income_growth,
    net_income_growth,
    net_income_cont_ops_growth,
    cfo_growth,
    fcf_growth,
    operation_revenue_growth_3_month_avg,
    gross_margin,
    operation_margin,
    pretax_margin,
    net_margin,
    tax_rate,
    ebit_margin,
    ebitda_margin,
    sales_per_employee,
    current_ratio,
    quick_ratio,
    long_term_debt_total_capital_ratio,
    interest_coverage,
    long_term_debt_equity_ratio,
    financial_leverage,
    total_debt_equity_ratio,
    normalized_net_profit_margin,
    days_in_sales,
    days_in_inventory,
    days_in_payment,
    cash_conversion_cycle,
    receivable_turnover,
    inventory_turnover,
    payment_turnover,
    fix_assets_turonver,
    assets_turnover,
    roe,
    roa,
    roic,
    fcf_sales_ratio,
    fcf_net_income_ratio,
    cap_ex_sales_ratio,
    debt_to_assets,
    common_equity_to_assets,
    capital_expenditure_annual_5_yr_growth,
    gross_profit_annual_5_yr_growth,
    gross_margin_5_yr_avg,
    post_tax_margin_5_yr_avg,
    pre_tax_margin_5_yr_avg,
    profit_margin_5_yr_avg,
    roe_5_yr_avg,
    roa_5_yr_avg,
    avg_5_yrs_roic,
    normalized_roic,
    regression_growth_operating_revenue_5_years,
    cash_ratio,
    cashto_total_assets,
    capital_expenditureto_ebitda,
    fc_fto_cfo,
    stockholders_equity_growth,
    total_assets_growth,
    total_liabilities_growth,
    total_debt_equity_ratio_growth,
    cash_ratio_growth,
    ebitda_growth,
    cash_flow_from_financing_growth,
    cash_flow_from_investing_growth,
    cap_ex_growth,
    current_ratio_growth,
    working_capital_turnover_ratio,
    net_income_per_employee,
    solvency_ratio,
    expense_ratio,
    loss_ratio,
    date TEXT
);

DROP TABLE IF EXISTS financial_earning_reports;

CREATE TABLE IF NOT EXISTS financial_earning_reports (
    symbol TEXT,
    recent_month TEXT,
    period_ending_date TEXT,
    file_date TEXT,
    accession_number,
    form_type,
    period_type,
    basic_continuous_operations,
    basic_discontinuous_operations,
    basic_extraordinary,
    basic_accounting_change,
    basic_eps,
    diluted_continuous_operations,
    diluted_discontinuous_operations,
    diluted_extraordinary,
    diluted_accounting_change,
    diluted_eps,
    basic_average_shares,
    diluted_average_shares,
    dividend_per_share,
    basic_eps_other_gains_losses,
    continuing_and_discontinued_basic_eps,
    tax_loss_carryforward_basic_eps,
    diluted_eps_other_gains_losses,
    continuing_and_discontinued_diluted_eps,
    tax_loss_carryforward_diluted_eps,
    normalized_basic_eps,
    normalized_diluted_eps,
    total_dividend_per_share,
    reported_normalized_basic_eps,
    reported_normalized_diluted_eps,
    dividend_coverage_ratio,
    date TEXT
);

DROP TABLE IF EXISTS financial_cash_flows;

CREATE TABLE IF NOT EXISTS financial_cash_flows (
    symbol TEXT,
    recent_month TEXT,
    cf_file_date TEXT,
    amortization,
    capital_expenditure,
    cash_dividends_paid,
    cash_flow_from_continuing_financing_activities,
    cash_flow_from_continuing_investing_activities,
    cash_flow_from_continuing_operating_activities,
    cash_flow_from_discontinued_operation,
    financing_cash_flow,
    investing_cash_flow,
    operating_cash_flow,
    beginning_cash_position,
    end_cash_position,
    cash_from_discontinued_financing_activities,
    cash_from_discontinued_investing_activities,
    change_in_account_payable,
    change_in_tax_payable,
    change_in_accrued_expense,
    change_in_accrued_investment_income,
    changes_in_cash,
    change_in_deferred_acquisition_costs,
    change_in_federal_funds_and_securities_sold_for_repurchase,
    change_in_funds_withheld,
    change_in_income_tax_payable,
    change_in_interest_payable,
    change_in_inventory,
    change_in_loans,
    change_in_loss_and_loss_adjustment_expense_reserves,
    change_in_payable,
    change_in_payables_and_accrued_expense,
    change_in_prepaid_assets,
    change_in_receivables,
    change_in_reinsurance_recoverable_on_paid_and_unpaid_losses,
    change_in_restricted_cash,
    change_in_trading_account_securities,
    change_in_working_capital,
    deferred_income_tax,
    deferred_tax,
    depletion,
    depreciation,
    depreciation_and_amortization,
    depreciation_amortization_depletion,
    effect_of_exchange_rate_changes,
    increase_decrease_in_deposit,
    net_common_stock_issuance,
    net_issuance_payments_of_debt,
    net_long_term_debt_issuance,
    net_preferred_stock_issuance,
    net_short_term_debt_issuance,
    net_cash_from_discontinued_operations,
    net_foreign_currency_exchange_gain_loss,
    net_income_from_continuing_operations,
    payment_for_loans,
    common_stock_payments,
    preferred_stock_payments,
    long_term_debt_payments,
    short_term_debt_payments,
    proceeds_from_loans,
    proceeds_from_stock_option_exercised,
    common_stock_issuance,
    long_term_debt_issuance,
    preferred_stock_issuance,
    short_term_debt_issuance,
    net_proceeds_payment_for_loan,
    proceeds_payment_in_interest_bearing_deposits_in_bank,
    purchase_of_intangibles,
    purchase_of_investment,
    purchase_of_ppe,
    purchase_of_business,
    net_business_purchase_and_sale,
    net_intangibles_purchase_and_sale,
    net_investment_purchase_and_sale,
    net_ppe_purchase_and_sale,
    sale_of_business,
    sale_of_intangibles,
    sale_of_investment,
    sale_of_ppe,
    changes_in_account_receivables,
    amortization_of_financing_costs_and_discounts,
    amortization_of_securities,
    asset_impairment_charge,
    change_in_dividend_payable,
    change_in_deferred_charges,
    change_in_other_current_assets,
    change_in_other_current_liabilities,
    change_in_other_working_capital,
    change_in_unearned_premiums,
    common_stock_dividend_paid,
    earnings_losses_from_equity_investments,
    excess_tax_benefit_from_stock_based_compensation,
    gain_loss_on_investment_securities,
    gain_loss_on_sale_of_business,
    gain_loss_on_sale_of_ppe,
    interest_credited_on_policyholder_deposits,
    cash_from_discontinued_operating_activities,
    operating_gains_losses,
    net_other_financing_charges,
    net_other_investing_changes,
    other_non_cash_items,
    pension_and_employee_benefit_expense,
    preferred_stock_dividend_paid,
    proceeds_payment_federal_funds_sold_and_securities_purchased_under_agreement_to_resell,
    provision_for_loan_lease_and_other_losses,
    realized_gain_loss_on_sale_of_loans_and_lease,
    stock_based_compensation,
    unrealized_gain_loss_on_investment_securities,
    unrealized_gains_losses_on_derivatives,
    amortization_of_intangibles,
    income_tax_paid_supplemental_data,
    interest_paid_supplemental_data,
    issuance_of_capital_stock,
    issuance_of_debt,
    repayment_of_debt,
    repurchase_of_capital_stock,
    free_cash_flow,
    decrease_in_interest_bearing_deposits_in_bank,
    increase_in_interest_bearing_deposits_in_bank,
    interest_received_cfo,
    interest_paid_cfo,
    purchase_of_subsidiaries,
    purchase_of_joint_venture_associate,
    sale_of_subsidiaries,
    sale_of_joint_venture_associate,
    increase_decrease_in_lease_financing,
    increase_in_lease_financing,
    repayment_in_lease_financing,
    share_of_associates,
    profit_on_disposals,
    reorganization_other_costs,
    net_outward_loans,
    issue_expenses,
    changein_depositsby_banksand_customers,
    cash_flowsfromusedin_operating_activities_direct,
    classesof_cash_receiptsfrom_operating_activities,
    other_cash_receiptsfrom_operating_activities,
    classesof_cash_payments,
    paymentsto_suppliersfor_goodsand_services,
    paymentson_behalfof_employees,
    other_cash_paymentsfrom_operating_activities,
    dividends_paid_direct,
    dividends_received_direct,
    interest_paid_direct,
    interest_received_direct,
    taxes_refund_paid_direct,
    total_adjustmentsfor_non_cash_items,
    impairment_loss_reversal_recognizedin_profitor_loss,
    dividend_paid_cfo,
    dividend_received_cfo,
    taxes_refund_paid,
    other_operating_inflows_outflowsof_cash,
    cash_advancesand_loans_madeto_other_parties,
    cash_receiptsfrom_repaymentof_advancesand_loans_madeto_other_parties,
    dividends_received_cfi,
    interest_received_cfi,
    interest_paid_cff,
    changein_accrued_income,
    changein_financial_assets,
    changein_advancesfrom_central_banks,
    changein_financial_liabilities,
    changein_insurance_contract_assets,
    changein_reinsurance_receivables,
    changein_deferred_acquisition_costs_net,
    changein_insurance_funds,
    changein_investment_contract_liabilities,
    changein_insurance_contract_liabilities,
    provisionand_write_offof_assets,
    receiptsfrom_customers,
    receiptsfrom_government_grants,
    minority_interest,
    cap_ex_reported,
    cash_receiptsfrom_tax_refunds,
    cash_receiptsfrom_depositsby_banksand_customers,
    cash_receiptsfrom_loans,
    cash_receiptsfrom_securities_related_activities,
    cash_receiptsfrom_feesand_commissions,
    cash_paymentsfor_depositsby_banksand_customers,
    cash_paymentsfor_loans,
    interestand_commission_paid,
    all_taxes_paid,
    cash_receivedfrom_insurance_activities,
    premium_received,
    reinsuranceand_other_recoveries_received,
    policyholder_deposit_investment_received,
    cash_paidfor_insurance_activities,
    claims_paid,
    commission_paid,
    cash_paidto_reinsurers,
    other_underwriting_expenses_paid,
    cash_dividends_for_minorities,
    cash_generatedfrom_operating_activities,
    fund_from_operation,
    net_investment_properties_purchase_and_sale,
    purchase_of_investment_properties,
    sale_of_investment_properties,
    other_cash_adjust_included_into_changein_cash,
    other_cash_adjust_exclude_from_changein_cash,
    changein_cash_supplemental_as_reported,
    date TEXT
);

DROP TABLE IF EXISTS financial_balance_sheets;

CREATE TABLE IF NOT EXISTS financial_balance_sheets (
    symbol TEXT,
    recent_month TEXT,
bs_file_date TEXT,
    accounts_payable,
    accounts_receivable,
    current_accrued_expenses,
    non_current_accrued_expenses,
    accrued_investment_income,
    accumulated_depreciation,
    gains_losses_not_affecting_retained_earnings,
    additional_paid_in_capital,
    allowance_for_loans_and_lease_losses,
    available_for_sale_securities,
    capital_stock,
    cash,
    cash_equivalents,
    cash_and_cash_equivalents,
    cash_and_due_from_banks,
    cash_cash_equivalents_and_federal_funds_sold,
    cash_cash_equivalents_and_marketable_securities,
    common_stock,
    current_assets,
    current_debt,
    current_debt_and_capital_lease_obligation,
    current_liabilities,
    current_capital_lease_obligation,
    deferred_assets,
    deferred_costs,
    non_current_deferred_liabilities,
    current_deferred_liabilities,
    deferred_policy_acquisition_costs,
    current_deferred_revenue,
    non_current_deferred_revenue,
    deferred_tax_assets,
    current_deferred_taxes_assets,
    current_deferred_taxes_liabilities,
    non_current_deferred_taxes_assets,
    non_current_deferred_taxes_liabilities,
    equity_investments,
    federal_funds_purchased_and_securities_sold_under_agreement_to_repurchase,
    federal_funds_sold_and_securities_purchase_under_agreements_to_resell,
    fixed_maturity_investments,
    future_policy_benefits,
    general_partnership_capital,
    goodwill,
    goodwill_and_other_intangible_assets,
    gross_loan,
    gross_ppe,
    held_to_maturity_securities,
    income_tax_payable,
    interest_bearing_deposits_liabilities,
    interest_payable,
    interest_bearing_deposits_assets,
    inventory,
    investments_and_advances,
    limited_partnership_capital,
    long_term_debt,
    long_term_debt_and_capital_lease_obligation,
    long_term_investments,
    long_term_capital_lease_obligation,
    minority_interest,
    money_market_investments,
    net_loan,
    net_ppe,
    non_interest_bearing_deposits,
    current_notes_payable,
    notes_receivable,
    non_current_note_receivables,
    other_current_liabilities,
    other_intangible_assets,
    other_short_term_investments,
    payables,
    payables_and_accrued_expenses,
    policy_reserves_benefits,
    policyholder_funds,
    preferred_securities_outside_stock_equity,
    preferred_stock,
    prepaid_assets,
    non_current_prepaid_assets,
    receivables,
    reinsurance_recoverable,
    retained_earnings,
    securities_lending_collateral,
    security_agree_to_be_resell,
    security_sold_not_yet_repurchased,
    separate_account_assets,
    separate_account_business,
    short_term_investments_available_for_sale,
    short_term_investments_held_to_maturity,
    short_term_investments_trading,
    stockholders_equity,
    total_tax_payable,
    total_assets,
    total_deposits,
    total_investments,
    total_non_current_assets,
    total_partnership_capital,
    trading_assets,
    trading_liabilities,
    trading_securities,
    treasury_stock,
    unearned_income,
    unearned_premiums,
    unpaid_loss_and_loss_reserve,
    invested_capital,
    current_deferred_assets,
    non_current_deferred_assets,
    securities_and_investments,
    total_liabilities_net_minority_interest,
    total_non_current_liabilities_net_minority_interest,
    total_equity_gross_minority_interest,
    gross_accounts_receivable,
    non_current_accounts_receivable,
    accrued_interest_receivable,
    advance_from_federal_home_loan_banks,
    allowance_for_doubtful_accounts_receivable,
    allowance_for_notes_receivable,
    assets_held_for_sale,
    assets_of_discontinued_operations,
    bank_indebtedness,
    bank_owned_life_insurance,
    security_borrowed,
    buildings_and_improvements,
    commercial_loan,
    commercial_paper,
    common_stock_equity,
    construction_in_progress,
    consumer_loan,
    minimum_pension_liabilities,
    customer_acceptances,
    defined_pension_benefit,
    derivative_product_liabilities,
    derivative_assets,
    dividends_payable,
    employee_benefits,
    federal_funds_purchased,
    federal_funds_sold,
    federal_home_loan_bank_stock,
    financial_assets,
    financial_instruments_sold_under_agreements_to_repurchase,
    finished_goods,
    flight_fleet_vehicle_and_related_equipments,
    foreclosed_assets,
    foreign_currency_translation_adjustments,
    inventories_adjustments_allowances,
    investments_in_other_ventures_under_equity_method,
    land_and_improvements,
    leases,
    liabilities_of_discontinued_operations,
    line_of_credit,
    loans_held_for_sale,
    loans_receivable,
    machinery_furniture_equipment,
    materials_and_supplies,
    mineral_properties,
    mortgage_loan,
    mortgage_and_consumerloans,
    gross_notes_receivable,
    other_assets,
    other_capital_stock,
    other_current_assets,
    other_current_borrowings,
    other_equity_adjustments,
    other_inventories,
    other_invested_assets,
    other_non_current_assets,
    other_properties,
    other_real_estate_owned,
    other_receivables,
    non_current_pension_and_other_postretirement_benefit_plans,
    policy_loans,
    preferred_stock_equity,
    properties,
    current_provisions,
    long_term_provisions,
    raw_materials,
    receivables_adjustments_allowances,
    regulatory_assets,
    regulatory_liabilities,
    reinsurance_balances_payable,
    restricted_cash,
    restricted_cash_and_cash_equivalents,
    restricted_cash_and_investments,
    restricted_common_stock,
    restricted_investments,
    taxes_receivable,
    total_capitalization,
    total_deferred_credits_and_other_non_current_liabilities,
    unbilled_receivables,
    unrealized_gain_loss,
    work_in_process,
    other_non_current_liabilities,
    capital_lease_obligations,
    other_liabilities,
    other_payable,
    tangible_book_value,
    total_equity,
    working_capital,
    total_debt,
    common_utility_plant,
    electric_utility_plant,
    natural_gas_fuel_and_other,
    net_utility_plant,
    water_production,
    ordinary_shares_number,
    preferred_shares_number,
    treasury_shares_number,
    trading_and_other_receivable,
    equity_attributable_to_owners_of_parent,
    securities_loaned,
    net_tangible_assets,
    duefrom_related_parties_current,
    duefrom_related_parties_non_current,
    dueto_related_parties,
    dueto_related_parties_current,
    dueto_related_parties_non_current,
    investment_properties,
    investmentsin_subsidiariesat_cost,
    investmentsin_associatesat_cost,
    investmentsin_joint_venturesat_cost,
    investmentin_financial_assets,
    finance_lease_receivables,
    convertible_loans_current,
    bank_loans_current,
    other_loans_current,
    accruedand_deferred_income,
    bank_loans_non_current,
    other_loans_non_current,
    other_reserves,
    loansand_advancesto_bank,
    loansand_advancesto_customer,
    treasury_billsand_other_eligible_bills,
    equity_shares_investments,
    depositsby_bank,
    customer_accounts,
    itemsin_the_courseof_transmissionto_other_banks,
    tradingand_financial_liabilities,
    debt_securitiesin_issue,
    subordinated_liabilities,
    provisions_total,
    operating_lease_assets,
    claims_outstanding,
    liabilities_heldfor_sale_current,
    liabilities_heldfor_sale_non_current,
    debt_securities,
    total_financial_lease_obligations,
    accruedand_deferred_income_current,
    accruedand_deferred_income_non_current,
    finance_lease_receivables_current,
    finance_lease_receivables_non_current,
    financial_liabilities_current,
    financial_liabilities_non_current,
    financial_assets_designatedas_fair_value_through_profitor_loss_total,
    taxes_assets_current,
    other_equity_interest,
    interest_bearing_borrowings_non_current,
    non_interest_bearing_borrowings_non_current,
    tradeand_other_payables_non_current,
    non_interest_bearing_borrowings_current,
    pensionand_other_post_retirement_benefit_plans_current,
    other_loan_assets,
    assets_pledgedas_collateral_subjectto_saleor_repledging_total,
    tax_assets_total,
    advancesfrom_central_banks,
    deposit_certificates,
    non_interest_bearing_borrowings_total,
    other_borrowed_funds,
    financial_liabilities_designatedas_fair_value_through_profitor_loss_total,
    financial_liabilities_measuredat_amortized_cost_total,
    accrued_liabilities_total,
    deferred_income_total,
    deferred_tax_liabilities_total,
    reinsurance_assets,
    deposits_madeunder_assumed_reinsurance_contract,
    insurance_contract_assets,
    insurance_contract_liabilities,
    deposits_receivedunder_ceded_insurance_contract,
    investment_contract_liabilities,
    pension_and_other_postretirement_benefit_plans_total,
    liabilities_heldfor_sale_total,
    hedging_assets_current,
    convertible_loans_total,
    bank_loans_total,
    other_loans_total,
    insurance_funds_non_current,
    debt_total,
    com_tre_sha_num,
    pre_tre_sha_num,
    net_debt,
    share_issued,
    assets_held_for_sale_current,
    assets_held_for_sale_non_current,
    biological_assets,
    cash_restricted_or_pledged,
    convertible_loans_non_current,
    financial_or_derivative_investment_current_liabilities,
    other_investments,
    trade_and_other_receivables_non_current,
    due_from_related_parties,
    unallocated_surplus,
    debt_due_in_year_1,
    debt_due_in_year_2,
    debt_due_in_year_5,
    debt_due_beyond,
    total_debt_in_maturity_schedule,
    fixed_assets_revaluation_reserve,
    current_other_financial_liabilities,
    non_current_other_financial_liabilities,
    other_financial_liabilities,
    total_liabilities_as_reported,
    total_equity_as_reported,
    date TEXT
);

DROP TABLE IF EXISTS financial_income_statements;

CREATE TABLE IF NOT EXISTS financial_income_statements (
    symbol TEXT,
    recent_month TEXT,
    is_file_date TEXT,
    amortization REAL,
    securities_amortization REAL,
    cost_of_revenue REAL,
    depletion REAL,
    depreciation REAL,
    depreciation_and_amortization REAL,
    depreciation_amortization_depletion REAL,
    net_income_discontinuous_operations REAL,
    excise_taxes REAL,
    net_income_extraordinary REAL,
    fee_revenue_and_other_income REAL,
    general_and_administrative_expense REAL,
    gross_profit,
    interest_expense,
    interest_expense_non_operating,
    interest_income_after_provision_for_loan_loss,
    interest_income_non_operating,
    net_non_operating_interest_income_expense,
    loss_adjustment_expense,
    minority_interests,
    net_income,
    net_income_common_stockholders,
    net_income_continuous_operations,
    net_interest_income,
    net_investment_income,
    total_revenue,
    non_interest_expense,
    non_interest_income,
    operating_expense,
    operating_income,
    operating_revenue,
    other_income_expense,
    policy_acquisition_expense,
    net_policyholder_benefits_and_claims,
    preferred_stock_dividends,
    total_premiums_earned,
    pretax_income,
    tax_provision,
    credit_losses_provision,
    research_and_development,
    selling_and_marketing_expense,
    selling_general_and_administration,
    special_income_charges,
    total_expenses,
    interest_income,
    ebit,
    ebitda,
    net_income_continuous_operations_net_minority_interest,
    ceded_premiums,
    commission_expenses,
    credit_card,
    dividend_income,
    earnings_from_equity_interest,
    equipment,
    exploration_development_and_mineral_property_lease_expenses,
    fees_and_commissions,
    foreign_exchange_trading_gains,
    fuel,
    fuel_and_purchase_power,
    gain_on_sale_of_business,
    gain_on_sale_of_ppe,
    gain_on_sale_of_security,
    gross_premiums_written,
    impairment_of_capital_assets,
    increase_decrease_in_net_unearned_premium_reserves,
    insurance_and_claims,
    interest_expense_for_deposit,
    interest_expense_for_federal_funds_sold_and_securities_purchase_under_agreements_to_resell,
    interest_expense_for_long_term_debt_and_capital_securities,
    interest_expense_for_short_term_debt,
    interest_income_from_deposits,
    interest_income_from_federal_funds_sold_and_securities_purchase_under_agreements_to_resell,
    interest_income_from_leases,
    interest_income_from_loans,
    interest_income_from_loans_and_lease,
    interest_income_from_securities,
    investment_banking_profit,
    maintenance_and_repairs,
    net_foreign_exchange_gain_loss,
    net_occupancy_expense,
    net_premiums_written,
    net_realized_gain_loss_on_investments,
    occupancy_and_equipment,
    operation_and_maintenance,
    other_customer_services,
    other_interest_expense,
    other_interest_income,
    other_non_interest_expense,
    other_special_charges,
    other_taxes,
    policyholder_benefits_ceded,
    policyholder_benefits_gross,
    policyholder_dividends,
    policyholder_interest,
    professional_expense_and_contract_services_expense,
    provision_for_doubtful_accounts,
    rent_and_landing_fees,
    restructuring_and_mergern_acquisition,
    salaries_and_wages,
    securities_activities,
    service_charge_on_depositor_accounts,
    trading_gain_loss,
    trust_feesby_commissions,
    underwriting_expenses,
    write_off,
    other_non_interest_income,
    amortization_of_intangibles,
    net_income_from_continuing_and_discontinued_operation,
    net_income_from_tax_loss_carryforward,
    other_operating_expenses,
    total_money_market_investments,
    reconciled_cost_of_revenue,
    reconciled_depreciation,
    normalized_income,
    net_income_from_continuing_operation_net_minority_interest,
    gain_losson_saleof_assets,
    gainon_saleof_loans,
    gainon_saleof_investment_property,
    losson_extinguishmentof_debt,
    earningsfrom_equity_interest_net_of_tax,
    net_income_including_noncontrolling_interests,
    otherunder_preferred_stock_dividend,
    staff_costs,
    social_security_costs,
    pension_costs,
    other_operating_income_total,
    incomefrom_associatesand_other_participating_interests,
    total_other_finance_cost,
    gross_dividend_payment,
    feesand_commission_income,
    feesand_commission_expense,
    net_trading_income,
    other_staff_costs,
    gainon_investment_properties,
    average_dilution_earnings,
    gain_losson_financial_instruments_designatedas_cash_flow_hedges,
    gain_losson_derecognitionof_available_for_sale_financial_assets,
    negative_goodwill_immediately_recognized,
    gains_losseson_financial_instruments_dueto_fair_value_adjustmentsin_hedge_accounting_total,
    impairment_losses_reversals_financial_instruments_net,
    claimsand_paid_incurred,
    reinsurance_recoveries_claimsand_benefits,
    changein_insurance_liabilities_netof_reinsurance,
    changein_investment_contract,
    credit_risk_provisions,
    wagesand_salaries,
    other_non_operating_income_expenses,
    other_non_operating_income,
    other_non_operating_expenses,
    total_unusual_items,
    total_unusual_items_excluding_goodwill,
    tax_rate_for_calcs,
    tax_effect_of_unusual_items,
    normalized_ebitda,
    stock_based_compensation,
    diluted_ni_availto_com_stockholders,
    investment_contract_liabilities_incurred,
    reinsurance_recoveriesof_investment_contract,
    total_dividend_paymentof_equity_shares,
    total_dividend_paymentof_non_equity_shares,
    changein_the_gross_provisionfor_unearned_premiums,
    changein_the_gross_provisionfor_unearned_premiums_reinsurers_share,
    claimsand_changein_insurance_liabilities,
    reinsurance_recoveriesof_insurance_liabilities,
    total_operating_income_as_reported,
    other_ga,
    other_costof_revenue,
    rentand_landing_fees_costof_revenue,
    dda_costof_revenue,
    rent_expense_supplemental,
    normalized_pre_tax_income,
    research_and_development_expenses_supplemental,
    depreciation_supplemental,
    amortization_supplemental,
    total_revenue_as_reported,
    operating_expense_as_reported,
    normalized_income_as_reported,
    normalized_ebitda_as_reported,
    normalized_ebit_as_reported,
    normalized_operating_profit_as_reported,
    effective_tax_rate_as_reported,
    date TEXT
);

DROP TABLE IF EXISTS financial_statements;

CREATE TABLE IF NOT EXISTS financial_statements (
  symbol TEXT,
  period_ending_date TEXT,
  recent_month TEXT,
  file_date TEXT,
  accession_number TEXT,
  form_type TEXT,
  period_auditor TEXT,
  auditor_report_status TEXT,
  inventory_valuation_method TEXT,
  number_of_share_holders TEXT,
  period_type TEXT,
  total_risk_based_capital TEXT
);

DROP TABLE IF EXISTS security_reference;

CREATE TABLE IF NOT EXISTS security_reference (
  security_symbol TEXT PRIMARY KEY,
  symbol TEXT,
  exchange_id TEXT,
  currency_id TEXT,
  ipo_date TEXT,
  is_depositary_receipt TEXT,
  depositary_receipt_ratio REAL,
  security_type TEXT,
  share_class_description TEXT,
  share_class_status TEXT,
  is_primary_share TEXT,
  is_dividend_reinvest TEXT,
  is_direct_invest TEXT,
  investment_id TEXT,
  ipo_offer_price REAL,
  delisting_date TEXT,
  delisting_reason TEXT,
  mic TEXT,
  common_share_sub_type TEXT,
  ipo_offer_price_range TEXT,
  exchange_sub_market_global_id TEXT,
  conversion_ration REAL,
  par_value REAL,
  trading_status TEXT,
  market_data_id TEXT,
  date TEXT
);

DROP TABLE IF EXISTS company_reference;

CREATE TABLE IF NOT EXISTS company_reference (
  company_id TEXT PRIMARY KEY,
  symbol TEXT,
  short_name TEXT,
  standard_name TEXT,
  legal_name TEXT,
  country_id TEXT,
  cik TEXT,
  company_status TEXT,
  fiscal_year_end INTEGER,
  industry_template_code TEXT,
  primary_share_class_id TEXT,
  primary_symbol TEXT,
  primary_exchange_id TEXT,
  business_country_id TEXT,
  legal_name_language_code TEXT,
  auditor TEXT,
  auditor_language_code TEXT,
  advisor TEXT,
  advisor_language_code TEXT,
  is_limited_partnership TEXT,
  is_reit TEXT,
  primary_mic TEXT,
  report_style INTEGER,
  yearof_establishment TEXT,
  is_limited_liability_company TEXT,
  expected_fiscal_year_end TEXT,
  date TEXT
);
